# Generated by Django 4.1.4 on 2023-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('precios', models.CharField(max_length=200)),
                ('Rubro', models.CharField(max_length=200)),
                ('Subrubro', models.CharField(max_length=200)),
                ('Presentacion', models.CharField(max_length=200)),
            ],
        ),
    ]
